apiVersion: v2
name: bk-user
description: A Helm chart for bk-user
type: application
version: 1.2.16
appVersion: "v2.3.4-beta.24"

dependencies:

- name: mariadb
  version: "9.x.x"
  repository: "https://charts.bitnami.com/bitnami"
  condition: mariadb.enabled

- name: redis
  version: "14.x.x"
  repository: "https://charts.bitnami.com/bitnami"
  condition: redis.enabled

- name: api
  version: "1.0.0"
  condition: api.enabled

- name: login
  version: "1.0.0"
  condition: login.enabled

- name: saas
  version: "1.0.0"
  condition: saas.enabled
