name: ESLint

on:
  push:
    branches: [ master, develop, pre_*, ft_* ]
  pull_request:
    branches: [ master, develop, pre_*, ft_* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: 'src/pages/yarn.lock'
    - name: Install modules
      run: |
        cd src/pages
        npm i
    - name: Run ESLint
      run: |
        cd src/pages
        npm run lint
