name: Python CI Check

on:
  push:
    branches: [ master, develop, pre_*, ft_* ]
  pull_request:
    branches: [ master, develop, pre_*, ft_* ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.1.7]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry==${{ matrix.poetry-version }} --include-deps requests==2.29.0
    - name: Export requirements.txt
      run: poetry export -f requirements.txt --dev --without-hashes -o requirements.txt --no-ansi
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
    - name: Install dependencies
      run: pip install -r requirements.txt -i https://pypi.org/simple/
    - name: Lint with flake8
      run: pflake8 src/ --config=pyproject.toml
    - name: Lint with mypy
      run:  mypy src/ --config-file=pyproject.toml
